version: '3.8'


services:
  

  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
    depends_on:
      - node-service

  node-service:
    build: ./docker/api
    environment:
       DB_HOST: db
       DB_USERNAME: karmdesai13
       DB_PASSWORD: secure_user_password
       DB_DATABASE: app_db
     
    depends_on:
      - db
  
  db:
    build: ./docker/db
      
    environment:
      MYSQL_ROOT_PASSWORD: secure_root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: karmdesai13
      MYSQL_PASSWORD: secure_user_password
    volumes:
      - db_data:/var/lib/mysql
  
volumes:
  db_data:
